version: "3.7"

networks:
  kong-poc:
    external: false

volumes:
  postgres_data:
    driver: local

services:
  kong-database:
    container_name: kong-database
    image: postgres:9.5
    deploy:
      restart_policy:
        condition: any
    networks:
      - kong-poc
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 10s
      timeout: 5s
      retries: 5

  kong-migration-bootstrap:
    container_name: kong-migration-bootstrap
    image: kong:3.2.2-alpine
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - kong-poc
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
    command: kong migrations bootstrap

  kong-migration-up:
    container_name: kong-migration-up
    image: kong:3.2.2-alpine
    networks:
      - kong-poc
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
    command: kong migrations up

  kong:
    container_name: kong
    image: kong:3.2.2-alpine
    networks:
      - kong-poc
    deploy:
      restart_policy:
        condition: any
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl http2
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_REAL_IP_RECURSIVE=on
      - KONG_NGINX_HTTP_RESOLVER=8.8.8.8
      - KONG_PLUGINS=bundled
    ports:
      - "8000:8000"
      - "443:8443"
      - "8001:8001"
    healthcheck:
      test: ["CMD", "wget", "-O-", "http://kong:8001/status"]
      interval: 5s
      retries: 10
    restart: on-failure
    # command: 
    #   - |
    #   - kong migrations bootstrap
    #   - kong migrations up

  players-api:
    container_name: players-api
    image: claudioed/players
    networks:
      - kong-poc
    deploy:
      restart_policy:
        condition: on-failure

  championships-api:
    container_name: championships-api
    image: claudioed/championships
    networks:
      - kong-poc
    deploy:
      restart_policy:
        condition: on-failure

  matches-api:
    container_name: matches-api
    image: claudioed/matches
    networks:
      - kong-poc
    deploy:
      restart_policy:
        condition: on-failure

  bets-api:
    container_name: bets-api
    image: claudioed/bets
    networks:
      - kong-poc
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "9999:9999"
    environment:
      - MATCH_SVC=http://matches-api:9999/api/matches/6c51d4dd-e277-4282-9c51-871ba7fb16b3
      - CHAMPIONSHIP_SVC=http://championships-api:9999/api/championships/144954fe-b6c3-4a51-80d3-92911a06265c
      - PLAYER_SVC=http://players-api:9999/api/players/144954fe-b6c3-4a51-80d3-92911a06265c

  postgres:
    container_name: postgres-database
    image: postgres
    networks:
      - kong-poc
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:legacy
    networks:
      - kong-poc
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  konga:
    container_name: konga
    image: pantsel/konga
    networks:
      - kong-poc
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - kong-database
    environment:
      NODE_ENV: development
    ports:
      - "1337:1337"
